### PR TITLE
feat/loading-spinner branch add

### PR DESCRIPTION
**Pull request by PriyanshuValiya**

### CODE REVIEW

**Comment by PriyanshuValiya** [comment]
Preview of Spinner

Screenshot 2024-10-19 170648

**Comment by bhavyaGP** [comment]
It should  show the internet speed in the speedometer, not just animation

**Comment by PriyanshuValiya** [comment]
Can you suggest a basic idea to show real-time speed in the speedometer, because it's already taking much time to show the final speed to user. In this case, we have to show any random numbers to the user in the speedometer. So I will add that functionality in this, if you allow me for that..

**Comment by PriyanshuValiya** [comment]
Demo Picture,

Screenshot 2024-10-19 202806

**Comment by bhavyaGP** [comment]
image
image

**Comment by PriyanshuValiya** [comment]
Yes, but how we will make it real time

**Pull request closed without merging**
