### PR TITLE
Speed Test Visualization

### PR DESCRIPTION
**Pull request by soni-shashan**

### CODE REVIEW

**Comment by soni-shashan** [comment]
closes #7

**Comment by soni-shashan** [comment]
https://github.com/user-attachments/assets/08585acd-d796-4081-9a6a-a04458e0cd6d

**Comment by soni-shashan** [comment]
Required dependencies added to package.json

**Comment by bhavyaGP** [comment]
Thank you for your valuable contribution !!
closes #7

**Pull request merged**
